### ISSUE TITLE
support v1 ?

### ISSUE THREAD

**Issue by JoeOrtiz** [h-michael/fluent-plugin-parse_cookie#4]
Curious if you plan on making this plugin support the new version of fluentd?

`"Plugin 'parse_cookie' does not support multi workers configuration (Fluent::ParseCookieOutput)`

**Comment by h-michael** [comment]
@JoeOrtiz
OK, I'll try in this weekend.

**Comment by h-michael** [comment]
@JoeOrtiz 
Now, Support above fluentd v0.14.0 and support multi workers.
