### ISSUE TITLE
BUG: use router.emit instead of Engine.emit

### ISSUE THREAD

**Issue by precs-sasaki** [h-michael/fluent-plugin-parse_cookie#8]
Appears due to the new fluentd , this error now pops up:
`[warn]: #0 out_parse_cookie: error_class:RuntimeError error_message:BUG: use router.emit instead of Engine.emit
`

https://www.fluentd.org/blog/fluentd-v0.10.58-is-released
https://github.com/fluent/fluentd/pull/511

**Comment by h-michael** [comment]
#10 has fixed this issue.
